-- MySQL Script generated by MySQL Workbench
-- Tue Jul  8 16:12:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_come_rapidito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_come_rapidito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_come_rapidito` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_come_rapidito` ;

-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`roles` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `rol_nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `numero_telefono` VARCHAR(50) NOT NULL,
  `correo_electronico` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `idRol` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `idRol` (`idRol` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`idRol`)
    REFERENCES `bd_come_rapidito`.`roles` (`idRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`carritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`carritos` (
  `id_carrito` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_carrito`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `carritos_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_come_rapidito`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`restaurantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`restaurantes` (
  `id_restaurante` INT NOT NULL AUTO_INCREMENT,
  `logo_url` VARCHAR(500) NULL DEFAULT NULL,
  `banner_url` VARCHAR(500) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(50) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `horario_apertura` TIME NULL DEFAULT NULL,
  `horario_cierre` TIME NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_restaurante`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `url_imagen` VARCHAR(500) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `id_categoria` INT NULL DEFAULT NULL,
  `id_restaurante` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `id_restaurante` (`id_restaurante` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `bd_come_rapidito`.`categorias` (`id_categoria`),
  CONSTRAINT `productos_ibfk_2`
    FOREIGN KEY (`id_restaurante`)
    REFERENCES `bd_come_rapidito`.`restaurantes` (`id_restaurante`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`detalles_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`detalles_carrito` (
  `id_detalle_carrito` INT NOT NULL AUTO_INCREMENT,
  `id_carrito` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_detalle_carrito`),
  INDEX `id_carrito` (`id_carrito` ASC) VISIBLE,
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `detalles_carrito_ibfk_1`
    FOREIGN KEY (`id_carrito`)
    REFERENCES `bd_come_rapidito`.`carritos` (`id_carrito`),
  CONSTRAINT `detalles_carrito_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `bd_come_rapidito`.`productos` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`direcciones` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `calle` VARCHAR(50) NOT NULL,
  `colonia` VARCHAR(50) NOT NULL,
  `numero_casa` VARCHAR(20) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(20) NULL DEFAULT NULL,
  `referencia` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `direcciones_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_come_rapidito`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `nombre_status` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_direccion` INT NOT NULL,
  `id_carrito` INT NOT NULL,
  `fecha_pedido` DATETIME NOT NULL,
  `tarifa` DECIMAL(10,2) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `id_status` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_direccion` (`id_direccion` ASC) VISIBLE,
  INDEX `id_carrito` (`id_carrito` ASC) VISIBLE,
  INDEX `id_status` (`id_status` ASC) VISIBLE,
  CONSTRAINT `pedidos_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_come_rapidito`.`usuarios` (`id_usuario`),
  CONSTRAINT `pedidos_ibfk_2`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `bd_come_rapidito`.`direcciones` (`id_direccion`),
  CONSTRAINT `pedidos_ibfk_3`
    FOREIGN KEY (`id_carrito`)
    REFERENCES `bd_come_rapidito`.`carritos` (`id_carrito`),
  CONSTRAINT `pedidos_ibfk_4`
    FOREIGN KEY (`id_status`)
    REFERENCES `bd_come_rapidito`.`status` (`id_status`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`vehiculos` (
  `id_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `nombre_vehiculo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_vehiculo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`transporte` (
  `id_transporte` INT NOT NULL AUTO_INCREMENT,
  `foto_vehiculo_url` VARCHAR(500) NULL DEFAULT NULL,
  `placas` VARCHAR(50) NOT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_vehiculo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_transporte`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_vehiculo` (`id_vehiculo` ASC) VISIBLE,
  CONSTRAINT `transporte_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_come_rapidito`.`usuarios` (`id_usuario`),
  CONSTRAINT `transporte_ibfk_2`
    FOREIGN KEY (`id_vehiculo`)
    REFERENCES `bd_come_rapidito`.`vehiculos` (`id_vehiculo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_come_rapidito`.`valoraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_come_rapidito`.`valoraciones` (
  `id_valoracion` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NULL DEFAULT NULL,
  `puntuacion_pedido` INT NULL DEFAULT NULL,
  `fecha_valoracion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_valoracion`),
  INDEX `id_pedido` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `valoraciones_ibfk_1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `bd_come_rapidito`.`pedidos` (`id_pedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
